### ISSUE TITLE
Multiple robots cannot be started

### ISSUE THREAD

**Issue by mcoffin** [mcoffin/rogue#15]
## Observed Behavior

When multiple robot bundles are loaded, error are received about `NetworkTables` having already been initialized.

```
07:50:53.236 [fileinstall-./deploy] WARN  org.apache.felix.fileinstall.3.5.0 - Error while starting bundle: file:/home/admin/rogue-launcher/deploy/simple-rogue-robot.jar
org.osgi.framework.BundleException: Activator start error in bundle simple-rogue-robot [30].
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:2270) ~[org.apache.felix.framework-5.2.0.jar:na]
    at org.apache.felix.framework.Felix.startBundle(Felix.java:2138) ~[org.apache.felix.framework-5.2.0.jar:na]
    at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:977) ~[org.apache.felix.framework-5.2.0.jar:na]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1245) ~[org.apache.felix.fileinstall-3.5.0.jar:3.5.0]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217) ~[org.apache.felix.fileinstall-3.5.0.jar:3.5.0]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:509) ~[org.apache.felix.fileinstall-3.5.0.jar:3.5.0]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358) ~[org.apache.felix.fileinstall-3.5.0.jar:3.5.0]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310) ~[org.apache.felix.fileinstall-3.5.0.jar:3.5.0]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: Network tables has already been initialized
  at mcoffin.rogue.example.HelloWorldRobot.<init>(HelloWorldRobot.scala:5)
  while locating mcoffin.rogue.example.HelloWorldRobot

1 error
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.robotBase$lzycompute(WpiActivator.scala:69) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.robotBase(WpiActivator.scala:66) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.prestart(WpiActivator.scala:82) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.prestart(WpiActivator.scala:87) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.prestart(WpiActivator.scala:87) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.prestart(WpiActivator.scala:73) ~[rogue-wpi.jar:na]
    at mcoffin.rogue.wpi.WpiActivator.start(WpiActivator.scala:103) ~[rogue-wpi.jar:na]
    at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697) ~[org.apache.felix.framework-5.2.0.jar:na]
    at org.apache.felix.framework.Felix.activateBundle(Felix.java:2220) ~[org.apache.felix.framework-5.2.0.jar:na]
    ... 7 common frames omitted
Caused by: java.lang.IllegalStateException: Network tables has already been initialized
    at edu.wpi.first.wpilibj.networktables.NetworkTable.checkInit(NetworkTable.java:45) ~[NetworkTables.jar:na]
    at edu.wpi.first.wpilibj.networktables.NetworkTable.setServerMode(NetworkTable.java:68) ~[NetworkTables.jar:na]
    at edu.wpi.first.wpilibj.RobotBase.<init>(RobotBase.java:58) ~[WPILib.jar:na]
    at edu.wpi.first.wpilibj.SampleRobot.<init>(SampleRobot.java:34) ~[WPILib.jar:na]
    at mcoffin.rogue.example.HelloWorldRobot.<init>(HelloWorldRobot.scala:5) ~[na:na]
    at mcoffin.rogue.example.HelloWorldRobot$$FastClassByGuice$$e63fd0c2.newInstance(<generated>) ~[na:na]
    at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:na]
    at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.0.jar:na]
    at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[guice-4.0.jar:na]
    ... 17 common frames omitted
```
## Desired Behavior

Multiple robot bundles should both initialize properly without any exceptions thrown. NetworkTables should only be initialized once.

**Comment by mcoffin** [comment]
It would be worth considering running a patched version of WPILib to solve this issue. Barring that, we _may_ have to come up with some runtime bytecode manipulation hack.

The root of the problem is that the constructor for `RobotBase` initializes NetworkTable, which throws exceptions when initialized multiple times. We've gotten around the double-initialization of the hardware config by not calling RobotBase.main, but it's going to be much harder to strip out calls to `<init>` from `RobotBase`.

**Comment by mcoffin** [comment]
I've kind of settled on the solution of running a patched version of WPILib, and containing a subproject for patching it, `wpilib-patcher`.
